#About this file
#The docker-compose.yml file is used to define the services, networks, and volumes that make up your application's environment. It allows you to specify configurations for multiple containers, their relationships, and how they communicate with each other.

#version of the docker-compose file
version: '3.9'

services:
  app:
    build:
        # build from the current directory
        context: .
        args:
          - DEV=true
    ports:
      - "8000:8000"
    volumes:
      # way of mapping local directory to container
      - ./app:/app
      - dev-static-data:/vol/web
    # For some reason it works on http://127.0.0.1:8000/
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - DEBUG=1
    #The app service will start after the db service by using depends on
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
  dev-static-data: