#version of the docker-compose file
version: '3.9'

services:
  app:
    build: 
        # build from the current directory
        context: .
        args: 
          - DEV=true
    ports:
      - "8000:8000"
    volumes:
      # way of mapping local directory to container 
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    #For some reason it works on http://127.0.0.1:8000/
  